services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $nodeManager: '@terminal42_node.manager'
            $bundles: '%kernel.bundles%'
    
    InspiredMinds\ContaoEventRegistration\:
        resource: ../src/
        exclude: ../src/{Config,DependencyInjection,Exception,Model}
